### ISSUE TITLE
core problem

### ISSUE THREAD

**Issue by vosi** [yourlabs/django-permissions-widget#2]
if i define my custom permission (ex. 'can_vote') - i will have an error, that can be fixed with 

@register.filter
def get_item(d, key):
    return d.get(key, None)

in template tag

but, them i have a table, where i can define 'can' to every possible permission....

**Comment by eriktelepovsky** [comment]
I created [pull request](https://github.com/yourlabs/django-permissions-widget/pull/3) for that.

**Comment by eriktelepovsky** [comment]
Done in version 1.1.0
